azs:
- name: dc1_z1
  cpi: dc1 
  cloud_properties:
    datacenters:
    - clusters: [((vcenter_dc1_cluster1)): {}]
- name: dc2_z1
  cpi: dc2 
  cloud_properties:
    datacenters:
    - clusters: [((vcenter_dc2_cluster1)): {}]

vm_types:
- name: default
  cloud_properties:
    cpu: 2
    ram: 2048
    disk: 10000 
- name: large
  cloud_properties:
    cpu: 2
    ram: 4096
    disk: 30_240

disk_types:
- name: default
  disk_size: 10_000
- name: large
  disk_size: 50_000

networks:
- name: default_dc1
  type: manual
  subnets:
  - range: ((bosh_cidr_dc1))
    gateway: ((bosh_internal_gw_dc1))
    azs: [dc1_z1]
    dns: ((bosh_dns_dc1))
    reserved: [((bosh_network_reserved_dc1))]
    static: [((bosh_network_static_dc1))]
    cloud_properties:
      name: ((bosh_vcenter_network_name_dc1))
- name: default_dc2
  type: manual
  subnets:
  - range: ((bosh_cidr_dc2))
    gateway: ((bosh_internal_gw_dc2))
    azs: [dc2_z1]
    dns: ((bosh_dns_dc2))
    reserved: [((bosh_network_reserved_dc1))]
    static: [((bosh_network_static_dc1))]
    cloud_properties:
      name: ((bosh_vcenter_network_name_dc1))

compilation:
  workers: 5
  reuse_compilation_vms: true
  az: dc1_z1
  vm_type: large
  network: default
