cpis:
- name: dc1 
  type: vsphere
  properties:
    host: ((vcenter_dc1_ip))
    user: ((vcenter_dc1_user))
    password: ((vcenter_dc1_password))
    datacenters:
    - clusters:
      - { ((vcenter_dc1_cluster1)): {}}
      datastore_pattern: ((vcenter_dc1_datastore))
      disk_path: ((folder_to_put_disks_in))
      name: ((vcenter_datacenter))
      persistent_datastore_pattern: ((vcenter_persistent_datastores_pattern))
      template_folder: ((folder_to_put_templates_in))
      vm_folder: ((folder_to_put_vms_in))

- name: dc2 
  type: vsphere
  properties:
    host: ((vcenter_ip))
    user: ((vcenter_user))
    password: ((vcenter_password))
    datacenters:
    - clusters:
      - { ((vcenter_cluster)): {}}
      datastore_pattern: ((vcenter_datastores_pattern))
      disk_path: ((folder_to_put_disks_in))
      name: ((vcenter_datacenter))
      persistent_datastore_pattern: ((vcenter_persistent_datastores_pattern))
      template_folder: ((folder_to_put_templates_in))
      vm_folder: ((folder_to_put_vms_in))
