cpis:
- name: dc1 
  type: vsphere
  properties:
    host: ((vcenter_dc1_ip))
    user: ((vcenter_dc1_user))
    password: ((vcenter_dc1_password))
    datacenters:
    - clusters:
      - { ((vcenter_dc1_cluster1)): {}}
      datastore_pattern: ((vcenter_dc1_datastore))
      name: ((vcenter_dc1_datacenter))
      persistent_datastore_pattern: ((vcenter_dc1_datastore))
      disk_path: ((director_name))-disks
      template_folder: ((director_name))-templates
      vm_folder: ((director_name))-vms


- name: dc2 
  type: vsphere
  properties:
    host: ((vcenter_dc2_ip))
    user: ((vcenter_dc2_user))
    password: ((vcenter_dc2_password))
    datacenters:
    - clusters:
      - { ((vcenter_dc2_cluster1)): {}}
      datastore_pattern: ((vcenter_dc2_datastore))
      name: ((vcenter_dc2_datacenter))
      persistent_datastore_pattern: ((vcenter_dc2_datastore))
      disk_path: ((director_name))-disks2
      template_folder: ((director_name))-templates2
      vm_folder: ((director_name))-vms2


