resources:
- name: concourse-bosh-deployment
  type: git
  source:
    uri: https://github.com/s-matyukevich/concourse-bosh-deployment.git

- name: bosh-deployment
  type: git
  source:
    uri: https://github.com/cloudfoundry/bosh-deployment.git

- name: bosh-version
  type: concourse-version-resource
  
resource_types:
- name: concourse-version-resource
  type: docker-image
  source:
    repository: meteogroup/concourse-version-resource
    tag: latest

jobs:
- name: deploy-bosh
  plan:
    - aggregate:
      - get: concourse-bosh-deployment
      - get: bosh-deployment
    - task: deploy-bosh
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: smatyukevich/docker-cfbosh
        run:
          path: concourse-bosh-deployment/ci/tasks/deploy-bosh.sh
        params:
          VAULT_ADDR: {{vault-addr}}
          VAULT_TOKEN: {{vault-token}}
          CONCOURSE_TEAM: {{concourse_team}}
          VM_PASSWORD: {{vm_password}}
          VCENTER_DC1_IP: {{vcenter_dc1_ip}}
          VCENTER_DC1_USER: {{vcenter_dc1_user}}
          VCENTER_DC1_PASSWORD: {{vcenter_dc1_password}}
          VCENTER_DC1_DATACENTER: {{vcenter_dc1_datacenter}}
          VCENTER_DC1_DATASTORE: {{vcenter_dc1_datastore}}
          VCENTER_DC1_CLUSTER1: {{vcenter_dc1_cluster1}}
          BOSH_INTERNAL_IP: {{bosh_internal_ip}}
          BOSH_EXTERNAL_IP: {{bosh_external_ip}}
          BOSH_CIDR: {{bosh_cidr}}
          BOSH_INTERNAL_GW: {{bosh_internal_gw}}
          BOSH_DNS: {{bosh_dns}}
          BOSH_NETWORK_RESERVED: {{bosh_network_reserved}}
          BOSH_VCENTER_NETWORK_NAME: {{bosh_vcenter_network_name}}
        inputs:
        - name: concourse-bosh-deployment
        - name: bosh-deployment
    - put: bosh-version

- name: update-cloudconfig 
  plan:
    - aggregate:
      - get: bosh-version
        trigger: true
        passed: [deploy-bosh]
      - get: concourse-bosh-deployment
      - get: bosh-deployment
    - task: update-cloudconfig
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: smatyukevich/docker-cfbosh
        run:
          path: concourse-bosh-deployment/ci/tasks/update-cloudconfig.sh
        params:
          VAULT_ADDR: {{vault-addr}}
          VAULT_TOKEN: {{vault-token}}
          CONCOURSE_TEAM: {{concourse_team}}
          BOSH_EXTERNAL_IP: {{bosh_external_ip}}

          VCENTER_DC1_IP: {{vcenter_dc1_ip}}
          VCENTER_DC1_USER: {{vcenter_dc1_user}}
          VCENTER_DC1_PASSWORD: {{vcenter_dc1_password}}
          VCENTER_DC1_DATACENTER: {{vcenter_dc1_datacenter}}
          VCENTER_DC1_DATASTORE: {{vcenter_dc1_datastore}}
          VCENTER_DC1_CLUSTER1: {{vcenter_dc1_cluster1}}

          VCENTER_DC2_IP: {{vcenter_dc2_ip}}
          VCENTER_DC2_USER: {{vcenter_dc2_user}}
          VCENTER_DC2_PASSWORD: {{vcenter_dc2_password}}
          VCENTER_DC2_DATACENTER: {{vcenter_dc2_datacenter}}
          VCENTER_DC2_DATASTORE: {{vcenter_dc2_datastore}}
          VCENTER_DC2_CLUSTER1: {{vcenter_dc2_cluster1}}

          BOSH_CIDR: {{bosh_cidr}}
          BOSH_INTERNAL_GW: {{bosh_internal_gw}}
          BOSH_DNS: {{bosh_dns}}
          BOSH_NETWORK_RESERVED: {{bosh_network_reserved}}
          BOSH_VCENTER_NETWORK_NAME: {{bosh_vcenter_network_name}}
        inputs:
        - name: concourse-bosh-deployment
        - name: bosh-deployment
